---
title: "AGU_GEDI_Workshop"
author: "Ivan Gonzalez, Melissa Rose, Jenna Keanny"
date: '2022-11-14'
output: html_document
---

User Inputs: 
```{r}
# Define working directory and create subdirectories
wd <- "C:/GEODE/agu_gedi_workshop/" 
dir.create(wd, recursive = TRUE, showWarnings = FALSE)
setwd(wd)

gL1B_data <- paste0(wd, 'data/GEDI01_B.002/')
dir.create(gL1B_data, recursive = TRUE, showWarnings = FALSE)
```
To Do: Update with folder structure from githib 


Dependencies:
```{r, warning=FALSE, message=FALSE}
# Define and install libraries to use
libs <- c('raster', 'devtools', 'sf', 'data.table', 'lidR', 'httr', 'rhdf5', 'curl')

installed_libs <- rownames(installed.packages())
sapply(libs, FUN = function(x){
  if (!x %in% installed_libs){
    install.packages(x)
  } 
})

library(raster)   
library(devtools) 
library(sf) 
library(data.table)
library(lidR)
library(httr)
library(tidyr)
library(curl)

# Import rGEDI functions
source(paste0(wd, 'scripts/rGEDI.R'))
```
To Do: Issue with rGEDI


Step 1: Define region(s) of interest 
```{r}
# ROI1: Amazon Basin
  #specifying bounding box coordinates
  ul_lat <- -2.745693 # upper left lat (ymax)
  ul_lon <- -62.345807 # upper left long (xmin)
  lr_lat <- -2.814620 # lower right lat (ymin)
  lr_lon <- -62.259633 # lower right long (xmax)

  #formatting bbox to identify overlapping GEDI orbits using gedi_finder
  amazon_bbox <- paste(ul_lon_trop, lr_lat_trop, lr_lon_trop, ul_lat_trop, sep = ',') # order of arguments: xmin ymin xmax ymax 


# ROI2: Tropical Dry Forest - 
  #specifying bounding box coordinates
  #ul_lat_temp <- 35.145706 # upper left lat (ymax)
  #ul_lon_temp <- -111.595149 # upper left long (xmin)
  #lr_lat_temp <- 56.930951 # lower right lat (ymin)
  #lr_lon_temp <- -133.702458 # lower right long (xmax)

  #formatting bbox to identify overlapping GEDI orbits using gedi_finder
  #temp_bbox <- paste(ul_lon_temp, lr_lat_temp, lr_lon_temp, ul_lat_temp, sep = ',') # order of arguments: xmin ymin xmax ymax 

# Specifying the date range to filter orbits by
daterange=c("2020-05-01","2020-07-31")
```
To Do: 
add map to show region of interests

Step 1: Use gediFinder to find overlapping GEDI orbits 
```{r}
# Call the gedi_finder() function to locate overlapping GEDI footprint
## ROI 1: Amazon
gL1B_amazon <- gedi_finder_temp_filter(roi_name = 'amazon', product = 'GEDI01_B.002', bbox = amazon_bbox, daterange = daterange, download_path = gL1B_data)

gediDownload(filepath=gL1B_amazon,outdir=gL1B_data)



```



Step 2: Read in HF file for each orbit 
```{r}
## Download the data:
str(found_orbits)
sapply(found_orbits$url, function(x){
  # x  = found_orbits$url[1]
  outName <- paste0(download_path, basename(x))
  # Download if doesn't exists
  if(!file.exists(outName)){
    download.file(url = x, destfile = outName)
  }
})
  
rGEDI::gediDownload(filepath = found_orbits$url, outdir = download_path)

if( is.null(gedi02b_list) ){
  load('GEDI_original_dataset.RData')
}
```


Step 3: 

